[package]
name = "huffman_module"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
bit_buffers = "0.1.2"
indexmap = "2.11.4"
shared_files ={ path = "../shared_files"}
